name: Robot recolector LotoAnalytics

on:
  schedule:
    - cron: '30 16,17,18,19,23,0,1,2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar archivos
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar librerías necesarias
        run: |
          npm init -y
          npm install axios cheerio jsdom express dotenv node-cron @supabase/supabase-js ws

      - name: Ejecutar backend-todo-en-uno
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node "backend-todo-en-uno (1).js"
